[2024-04-04T11:45:13.297+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___dbt.dbt_data_quality_checks manual__2024-04-04T11:44:44.417528+00:00 [queued]>
[2024-04-04T11:45:13.309+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___dbt.dbt_data_quality_checks manual__2024-04-04T11:44:44.417528+00:00 [queued]>
[2024-04-04T11:45:13.310+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-04T11:45:13.338+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_data_quality_checks> on 2024-04-04 11:44:44.417528+00:00
[2024-04-04T11:45:13.347+0000] {standard_task_runner.py:60} INFO - Started process 6997 to run task
[2024-04-04T11:45:13.352+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___dbt', 'dbt_data_quality_checks', 'manual__2024-04-04T11:44:44.417528+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/freshness_test_dag.py', '--cfg-path', '/tmp/tmpixzfo60n']
[2024-04-04T11:45:13.357+0000] {standard_task_runner.py:88} INFO - Job 409: Subtask dbt_data_quality_checks
[2024-04-04T11:45:13.441+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___dbt.dbt_data_quality_checks manual__2024-04-04T11:44:44.417528+00:00 [running]> on host 62dc842f1ceb
[2024-04-04T11:45:13.598+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___dbt' AIRFLOW_CTX_TASK_ID='dbt_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T11:44:44.417528+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-04T11:44:44.417528+00:00'
[2024-04-04T11:45:13.601+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-04T11:45:13.605+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-04T11:45:13.627+0000] {subprocess.py:86} INFO - Output:
[2024-04-04T11:45:18.067+0000] {subprocess.py:93} INFO - [0m11:45:18  Running with dbt=1.7.10
[2024-04-04T11:45:18.881+0000] {subprocess.py:93} INFO - [0m11:45:18  Registered adapter: postgres=1.7.10
[2024-04-04T11:45:32.605+0000] {subprocess.py:93} INFO - [0m11:45:32  Found 34 models, 2 operations, 6 tests, 1 source, 0 exposures, 0 metrics, 1407 macros, 0 groups, 0 semantic models
[2024-04-04T11:45:32.611+0000] {subprocess.py:93} INFO - [0m11:45:32
[2024-04-04T11:45:33.054+0000] {subprocess.py:93} INFO - [0m11:45:33
[2024-04-04T11:45:33.056+0000] {subprocess.py:93} INFO - [0m11:45:33  Running 1 on-run-start hook
[2024-04-04T11:45:33.221+0000] {subprocess.py:93} INFO - [0m11:45:33  1 of 1 START hook: elementary.on-run-start.0 ................................... [RUN]
[2024-04-04T11:45:33.223+0000] {subprocess.py:93} INFO - [0m11:45:33  1 of 1 OK hook: elementary.on-run-start.0 ...................................... [[32mOK[0m in 0.00s]
[2024-04-04T11:45:33.224+0000] {subprocess.py:93} INFO - [0m11:45:33
[2024-04-04T11:45:33.228+0000] {subprocess.py:93} INFO - [0m11:45:33  Concurrency: 1 threads (target='dev')
[2024-04-04T11:45:33.230+0000] {subprocess.py:93} INFO - [0m11:45:33
[2024-04-04T11:45:33.243+0000] {subprocess.py:93} INFO - [0m11:45:33  1 of 6 START test elementary_freshness_anomalies_raw_orders_creation_date ...... [RUN]
[2024-04-04T11:45:33.890+0000] {subprocess.py:93} INFO - [0m11:45:33  Elementary: Started running data monitors on: POSTGRES.PUBLIC.RAW_ORDERS
[2024-04-04T11:45:34.468+0000] {subprocess.py:93} INFO - [0m11:45:34  Elementary: Finished running data monitors on: POSTGRES.PUBLIC.RAW_ORDERS
[2024-04-04T11:45:35.232+0000] {subprocess.py:93} INFO - [0m11:45:35  1 of 6 PASS elementary_freshness_anomalies_raw_orders_creation_date ............ [[32mPASS[0m in 1.99s]
[2024-04-04T11:45:35.238+0000] {subprocess.py:93} INFO - [0m11:45:35  2 of 6 START test not_null_my_first_dbt_model_id ............................... [RUN]
[2024-04-04T11:45:35.424+0000] {subprocess.py:93} INFO - [0m11:45:35  2 of 6 FAIL 1 not_null_my_first_dbt_model_id ................................... [[31mFAIL 1[0m in 0.18s]
[2024-04-04T11:45:35.430+0000] {subprocess.py:93} INFO - [0m11:45:35  3 of 6 START test not_null_my_second_dbt_model_id .............................. [RUN]
[2024-04-04T11:45:35.727+0000] {subprocess.py:93} INFO - [0m11:45:35  3 of 6 PASS not_null_my_second_dbt_model_id .................................... [[32mPASS[0m in 0.30s]
[2024-04-04T11:45:35.733+0000] {subprocess.py:93} INFO - [0m11:45:35  4 of 6 START test not_null_raw_orders_creation_date ............................ [RUN]
[2024-04-04T11:45:35.900+0000] {subprocess.py:93} INFO - [0m11:45:35  4 of 6 PASS not_null_raw_orders_creation_date .................................. [[32mPASS[0m in 0.17s]
[2024-04-04T11:45:35.906+0000] {subprocess.py:93} INFO - [0m11:45:35  5 of 6 START test unique_my_first_dbt_model_id ................................. [RUN]
[2024-04-04T11:45:36.075+0000] {subprocess.py:93} INFO - [0m11:45:36  5 of 6 PASS unique_my_first_dbt_model_id ....................................... [[32mPASS[0m in 0.17s]
[2024-04-04T11:45:36.081+0000] {subprocess.py:93} INFO - [0m11:45:36  6 of 6 START test unique_my_second_dbt_model_id ................................ [RUN]
[2024-04-04T11:45:36.247+0000] {subprocess.py:93} INFO - [0m11:45:36  6 of 6 PASS unique_my_second_dbt_model_id ...................................... [[32mPASS[0m in 0.16s]
[2024-04-04T11:45:36.324+0000] {subprocess.py:93} INFO - [0m11:45:36
[2024-04-04T11:45:36.326+0000] {subprocess.py:93} INFO - [0m11:45:36  Running 1 on-run-end hook
[2024-04-04T11:45:39.338+0000] {subprocess.py:93} INFO - [0m11:45:39  1 of 1 START hook: elementary.on-run-end.0 ..................................... [RUN]
[2024-04-04T11:45:39.340+0000] {subprocess.py:93} INFO - [0m11:45:39  1 of 1 OK hook: elementary.on-run-end.0 ........................................ [[32mOK[0m in 0.00s]
[2024-04-04T11:45:39.342+0000] {subprocess.py:93} INFO - [0m11:45:39
[2024-04-04T11:45:39.349+0000] {subprocess.py:93} INFO - [0m11:45:39
[2024-04-04T11:45:39.352+0000] {subprocess.py:93} INFO - [0m11:45:39  Finished running 6 tests, 2 hooks in 0 hours 0 minutes and 6.74 seconds (6.74s).
[2024-04-04T11:45:39.432+0000] {subprocess.py:93} INFO - [0m11:45:39
[2024-04-04T11:45:39.434+0000] {subprocess.py:93} INFO - [0m11:45:39  [31mCompleted with 1 error and 0 warnings:[0m
[2024-04-04T11:45:39.436+0000] {subprocess.py:93} INFO - [0m11:45:39
[2024-04-04T11:45:39.437+0000] {subprocess.py:93} INFO - [0m11:45:39  [31mFailure in test not_null_my_first_dbt_model_id (models/example/schema.yml)[0m
[2024-04-04T11:45:39.438+0000] {subprocess.py:93} INFO - [0m11:45:39    Got 1 result, configured to fail if != 0
[2024-04-04T11:45:39.440+0000] {subprocess.py:93} INFO - [0m11:45:39
[2024-04-04T11:45:39.441+0000] {subprocess.py:93} INFO - [0m11:45:39    compiled Code at target/compiled/proj/models/example/schema.yml/not_null_my_first_dbt_model_id.sql
[2024-04-04T11:45:39.443+0000] {subprocess.py:93} INFO - [0m11:45:39
[2024-04-04T11:45:39.444+0000] {subprocess.py:93} INFO - [0m11:45:39  Done. PASS=5 WARN=0 ERROR=1 SKIP=0 TOTAL=6
[2024-04-04T11:45:40.368+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-04T11:45:40.385+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-04T11:45:40.391+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag___dbt, task_id=dbt_data_quality_checks, execution_date=20240404T114444, start_date=20240404T114513, end_date=20240404T114540
[2024-04-04T11:45:40.412+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 409 for task dbt_data_quality_checks (Bash command failed. The command returned a non-zero exit code 1.; 6997)
[2024-04-04T11:45:40.451+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-04T11:45:40.485+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
