[2024-04-01T09:56:41.429+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___dbt.dbt_freshness_check scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-01T09:56:41.458+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___dbt.dbt_freshness_check scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-01T09:56:41.459+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-01T09:56:41.500+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_freshness_check> on 2024-03-30 00:00:00+00:00
[2024-04-01T09:56:41.513+0000] {standard_task_runner.py:60} INFO - Started process 648 to run task
[2024-04-01T09:56:41.528+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___dbt', 'dbt_freshness_check', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/freshness_test_dag.py', '--cfg-path', '/tmp/tmpze9jkovc']
[2024-04-01T09:56:41.533+0000] {standard_task_runner.py:88} INFO - Job 118: Subtask dbt_freshness_check
[2024-04-01T09:56:41.739+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___dbt.dbt_freshness_check scheduled__2024-03-30T00:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-01T09:56:41.972+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___dbt' AIRFLOW_CTX_TASK_ID='dbt_freshness_check' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-30T00:00:00+00:00'
[2024-04-01T09:56:41.977+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T09:56:41.985+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-01T09:56:42.007+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T09:56:52.056+0000] {subprocess.py:93} INFO - [0m09:56:52  Running with dbt=1.7.10
[2024-04-01T09:56:53.863+0000] {subprocess.py:93} INFO - [0m09:56:53  Registered adapter: postgres=1.7.10
[2024-04-01T09:57:13.748+0000] {subprocess.py:93} INFO - [0m09:57:13  Encountered an error:
[2024-04-01T09:57:13.750+0000] {subprocess.py:93} INFO - [Errno 5] Input/output error: '/opt/***/proj/dbt_packages/elementary/models/edr/data_monitoring/anomaly_detection/metrics_anomaly_score.sql'
[2024-04-01T09:57:13.790+0000] {subprocess.py:93} INFO - [0m09:57:13  Traceback (most recent call last):
[2024-04-01T09:57:13.799+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
[2024-04-01T09:57:13.800+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-04-01T09:57:13.802+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 76, in wrapper
[2024-04-01T09:57:13.804+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:57:13.815+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 169, in wrapper
[2024-04-01T09:57:13.816+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:57:13.817+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 198, in wrapper
[2024-04-01T09:57:13.817+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:57:13.818+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 245, in wrapper
[2024-04-01T09:57:13.847+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:57:13.849+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 271, in wrapper
[2024-04-01T09:57:13.851+0000] {subprocess.py:93} INFO -     ctx.obj["manifest"] = parse_manifest(
[2024-04-01T09:57:13.852+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 1798, in parse_manifest
[2024-04-01T09:57:13.854+0000] {subprocess.py:93} INFO -     manifest = ManifestLoader.get_full_manifest(
[2024-04-01T09:57:13.855+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 318, in get_full_manifest
[2024-04-01T09:57:13.861+0000] {subprocess.py:93} INFO -     manifest = loader.load()
[2024-04-01T09:57:13.865+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 365, in load
[2024-04-01T09:57:13.901+0000] {subprocess.py:93} INFO -     file_reader.read_files()
[2024-04-01T09:57:13.902+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 203, in read_files
[2024-04-01T09:57:13.903+0000] {subprocess.py:93} INFO -     self.read_files_for_project(project, file_types)
[2024-04-01T09:57:13.913+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 210, in read_files_for_project
[2024-04-01T09:57:13.924+0000] {subprocess.py:93} INFO -     project_files[file_type_info["parser"]] = read_files_for_parser(
[2024-04-01T09:57:13.936+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 158, in read_files_for_parser
[2024-04-01T09:57:13.942+0000] {subprocess.py:93} INFO -     source_files = get_source_files(
[2024-04-01T09:57:13.944+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 134, in get_source_files
[2024-04-01T09:57:13.946+0000] {subprocess.py:93} INFO -     fp_list = filesystem_search(project, paths, extension, ignore_spec)
[2024-04-01T09:57:13.955+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/search.py", line 74, in filesystem_search
[2024-04-01T09:57:13.958+0000] {subprocess.py:93} INFO -     for result in find_matching(root, relative_dirs, ext, ignore_spec):
[2024-04-01T09:57:13.959+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/clients/system.py", line 79, in find_matching
[2024-04-01T09:57:13.960+0000] {subprocess.py:93} INFO -     modification_time = os.path.getmtime(absolute_path)
[2024-04-01T09:57:13.961+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/genericpath.py", line 55, in getmtime
[2024-04-01T09:57:13.962+0000] {subprocess.py:93} INFO -     return os.stat(filename).st_mtime
[2024-04-01T09:57:13.963+0000] {subprocess.py:93} INFO - OSError: [Errno 5] Input/output error: '/opt/***/proj/dbt_packages/elementary/models/edr/data_monitoring/anomaly_detection/metrics_anomaly_score.sql'
[2024-04-01T09:57:13.964+0000] {subprocess.py:93} INFO - 
[2024-04-01T09:57:15.954+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-01T09:57:16.266+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T09:57:16.452+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
