[2024-04-01T10:05:19.020+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___freshness.run_model1 scheduled__2024-03-17T12:00:00+00:00 [queued]>
[2024-04-01T10:05:19.238+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___freshness.run_model1 scheduled__2024-03-17T12:00:00+00:00 [queued]>
[2024-04-01T10:05:19.242+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-01T10:05:19.561+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-03-17 12:00:00+00:00
[2024-04-01T10:05:19.676+0000] {standard_task_runner.py:60} INFO - Started process 1253 to run task
[2024-04-01T10:05:19.745+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___freshness', 'run_model1', 'scheduled__2024-03-17T12:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/freshness_test_dag.py', '--cfg-path', '/tmp/tmpbnpr5ywt']
[2024-04-01T10:05:19.761+0000] {standard_task_runner.py:88} INFO - Job 194: Subtask run_model1
[2024-04-01T10:05:20.292+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___freshness.run_model1 scheduled__2024-03-17T12:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-01T10:05:20.789+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___freshness' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-17T12:00:00+00:00'
[2024-04-01T10:05:20.803+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T10:05:20.809+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models my_first_dbt_model my_second_dbt_model  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-01T10:05:20.865+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T10:05:53.409+0000] {subprocess.py:93} INFO - [0m10:05:53  Running with dbt=1.7.10
[2024-04-01T10:05:56.277+0000] {subprocess.py:93} INFO - [0m10:05:56  Registered adapter: postgres=1.7.10
[2024-04-01T10:06:14.889+0000] {subprocess.py:93} INFO - [0m10:06:14  Found 34 models, 2 operations, 5 tests, 1 source, 0 exposures, 0 metrics, 1407 macros, 0 groups, 0 semantic models
[2024-04-01T10:06:14.905+0000] {subprocess.py:93} INFO - [0m10:06:14
[2024-04-01T10:06:16.552+0000] {subprocess.py:93} INFO - [0m10:06:16
[2024-04-01T10:06:16.574+0000] {subprocess.py:93} INFO - [0m10:06:16  Running 1 on-run-start hook
[2024-04-01T10:06:16.977+0000] {subprocess.py:93} INFO - [0m10:06:16  1 of 1 START hook: elementary.on-run-start.0 ................................... [RUN]
[2024-04-01T10:06:16.988+0000] {subprocess.py:93} INFO - [0m10:06:16  1 of 1 OK hook: elementary.on-run-start.0 ...................................... [[32mOK[0m in 0.00s]
[2024-04-01T10:06:16.993+0000] {subprocess.py:93} INFO - [0m10:06:16
[2024-04-01T10:06:17.037+0000] {subprocess.py:93} INFO - [0m10:06:17  Concurrency: 1 threads (target='dev')
[2024-04-01T10:06:17.052+0000] {subprocess.py:93} INFO - [0m10:06:17
[2024-04-01T10:06:17.127+0000] {subprocess.py:93} INFO - [0m10:06:17  1 of 2 START sql table model public.my_first_dbt_model ......................... [RUN]
[2024-04-01T10:06:17.691+0000] {subprocess.py:93} INFO - [0m10:06:17  1 of 2 ERROR creating sql table model public.my_first_dbt_model ................ [[31mERROR[0m in 0.55s]
[2024-04-01T10:06:17.706+0000] {subprocess.py:93} INFO - [0m10:06:17  2 of 2 SKIP relation public.my_second_dbt_model ................................ [[33mSKIP[0m]
[2024-04-01T10:06:17.866+0000] {subprocess.py:93} INFO - [0m10:06:17
[2024-04-01T10:06:17.872+0000] {subprocess.py:93} INFO - [0m10:06:17  Running 1 on-run-end hook
[2024-04-01T10:06:26.526+0000] {subprocess.py:93} INFO - [0m10:06:26  1 of 1 START hook: elementary.on-run-end.0 ..................................... [RUN]
[2024-04-01T10:06:26.530+0000] {subprocess.py:93} INFO - [0m10:06:26  1 of 1 OK hook: elementary.on-run-end.0 ........................................ [[32mOK[0m in 0.00s]
[2024-04-01T10:06:26.535+0000] {subprocess.py:93} INFO - [0m10:06:26
[2024-04-01T10:06:26.551+0000] {subprocess.py:93} INFO - [0m10:06:26
[2024-04-01T10:06:26.562+0000] {subprocess.py:93} INFO - [0m10:06:26  Finished running 1 table model, 1 view model, 2 hooks in 0 hours 0 minutes and 11.64 seconds (11.64s).
[2024-04-01T10:06:26.785+0000] {subprocess.py:93} INFO - [0m10:06:26
[2024-04-01T10:06:26.808+0000] {subprocess.py:93} INFO - [0m10:06:26  [31mCompleted with 1 error and 0 warnings:[0m
[2024-04-01T10:06:26.814+0000] {subprocess.py:93} INFO - [0m10:06:26
[2024-04-01T10:06:26.818+0000] {subprocess.py:93} INFO - [0m10:06:26    Database Error in model my_first_dbt_model (models/example/my_first_dbt_model.sql)
[2024-04-01T10:06:26.819+0000] {subprocess.py:93} INFO -   ERREUR:  erreur de syntaxe sur ou prÃ¨s de Â« external Â»
[2024-04-01T10:06:26.820+0000] {subprocess.py:93} INFO -   LINE 2: drop external if exists "postgres"."public"."my_first_dbt_mo...
[2024-04-01T10:06:26.821+0000] {subprocess.py:93} INFO -                ^
[2024-04-01T10:06:26.822+0000] {subprocess.py:93} INFO - [0m10:06:26
[2024-04-01T10:06:26.830+0000] {subprocess.py:93} INFO - [0m10:06:26  Done. PASS=0 WARN=0 ERROR=1 SKIP=1 TOTAL=2
[2024-04-01T10:06:28.068+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-01T10:06:28.098+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-01T10:06:28.108+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag___freshness, task_id=run_model1, execution_date=20240317T120000, start_date=20240401T100519, end_date=20240401T100628
[2024-04-01T10:06:28.156+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 194 for task run_model1 (Bash command failed. The command returned a non-zero exit code 1.; 1253)
[2024-04-01T10:06:28.186+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T10:06:28.256+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
