[2024-04-01T10:09:56.949+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: freshness___dbt.run_model1 scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-04-01T10:09:57.036+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: freshness___dbt.run_model1 scheduled__2024-03-22T00:00:00+00:00 [queued]>
[2024-04-01T10:09:57.040+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-01T10:09:57.158+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-03-22 00:00:00+00:00
[2024-04-01T10:09:57.189+0000] {standard_task_runner.py:60} INFO - Started process 1527 to run task
[2024-04-01T10:09:57.220+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'freshness___dbt', 'run_model1', 'scheduled__2024-03-22T00:00:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/freshness_dag.py', '--cfg-path', '/tmp/tmp43g971uf']
[2024-04-01T10:09:57.235+0000] {standard_task_runner.py:88} INFO - Job 219: Subtask run_model1
[2024-04-01T10:09:57.439+0000] {task_command.py:423} INFO - Running <TaskInstance: freshness___dbt.run_model1 scheduled__2024-03-22T00:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-01T10:09:57.821+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='freshness___dbt' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-22T00:00:00+00:00'
[2024-04-01T10:09:57.876+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T10:09:57.890+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-01T10:09:57.953+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T10:10:26.261+0000] {subprocess.py:93} INFO - [0m10:10:26  Running with dbt=1.7.10
[2024-04-01T10:10:29.183+0000] {subprocess.py:93} INFO - [0m10:10:29  Registered adapter: postgres=1.7.10
[2024-04-01T10:10:33.841+0000] {subprocess.py:93} INFO - [0m10:10:33  Encountered an error:
[2024-04-01T10:10:33.843+0000] {subprocess.py:93} INFO - [Errno 5] Input/output error: '/opt/***/proj/dbt_packages/dbt_expectations/macros/schema_tests/aggregate_functions/expect_column_mean_to_be_between.sql'
[2024-04-01T10:10:33.854+0000] {subprocess.py:93} INFO - [0m10:10:33  Traceback (most recent call last):
[2024-04-01T10:10:33.855+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
[2024-04-01T10:10:33.857+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-04-01T10:10:33.858+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 76, in wrapper
[2024-04-01T10:10:33.859+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:10:33.862+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 169, in wrapper
[2024-04-01T10:10:33.863+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:10:33.864+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 198, in wrapper
[2024-04-01T10:10:33.867+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:10:33.869+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 245, in wrapper
[2024-04-01T10:10:33.870+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:10:33.871+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 271, in wrapper
[2024-04-01T10:10:33.872+0000] {subprocess.py:93} INFO -     ctx.obj["manifest"] = parse_manifest(
[2024-04-01T10:10:33.873+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 1798, in parse_manifest
[2024-04-01T10:10:33.875+0000] {subprocess.py:93} INFO -     manifest = ManifestLoader.get_full_manifest(
[2024-04-01T10:10:33.881+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 318, in get_full_manifest
[2024-04-01T10:10:33.882+0000] {subprocess.py:93} INFO -     manifest = loader.load()
[2024-04-01T10:10:33.883+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 365, in load
[2024-04-01T10:10:33.885+0000] {subprocess.py:93} INFO -     file_reader.read_files()
[2024-04-01T10:10:33.887+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 203, in read_files
[2024-04-01T10:10:33.888+0000] {subprocess.py:93} INFO -     self.read_files_for_project(project, file_types)
[2024-04-01T10:10:33.889+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 210, in read_files_for_project
[2024-04-01T10:10:33.890+0000] {subprocess.py:93} INFO -     project_files[file_type_info["parser"]] = read_files_for_parser(
[2024-04-01T10:10:33.892+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 158, in read_files_for_parser
[2024-04-01T10:10:33.894+0000] {subprocess.py:93} INFO -     source_files = get_source_files(
[2024-04-01T10:10:33.896+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 147, in get_source_files
[2024-04-01T10:10:33.906+0000] {subprocess.py:93} INFO -     file = load_source_file(fp, parse_file_type, project.project_name, saved_files)
[2024-04-01T10:10:33.909+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 75, in load_source_file
[2024-04-01T10:10:33.914+0000] {subprocess.py:93} INFO -     file_contents = load_file_contents(path.absolute_path, strip=True)
[2024-04-01T10:10:33.919+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/clients/system.py", line 97, in load_file_contents
[2024-04-01T10:10:33.924+0000] {subprocess.py:93} INFO -     with open(path, "rb") as handle:
[2024-04-01T10:10:33.927+0000] {subprocess.py:93} INFO - OSError: [Errno 5] Input/output error: '/opt/***/proj/dbt_packages/dbt_expectations/macros/schema_tests/aggregate_functions/expect_column_mean_to_be_between.sql'
[2024-04-01T10:10:33.929+0000] {subprocess.py:93} INFO - 
[2024-04-01T10:10:35.123+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-01T10:10:35.151+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-01T10:10:35.163+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=freshness___dbt, task_id=run_model1, execution_date=20240322T000000, start_date=20240401T100956, end_date=20240401T101035
[2024-04-01T10:10:35.227+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 219 for task run_model1 (Bash command failed. The command returned a non-zero exit code 2.; 1527)
[2024-04-01T10:10:35.275+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T10:10:35.352+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
