[2024-04-01T10:04:58.042+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___freshness.run_model1 scheduled__2024-03-15T05:00:00+00:00 [queued]>
[2024-04-01T10:04:58.178+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___freshness.run_model1 scheduled__2024-03-15T05:00:00+00:00 [queued]>
[2024-04-01T10:04:58.181+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-01T10:04:58.328+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-03-15 05:00:00+00:00
[2024-04-01T10:04:58.343+0000] {standard_task_runner.py:60} INFO - Started process 1228 to run task
[2024-04-01T10:04:58.383+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___freshness', 'run_model1', 'scheduled__2024-03-15T05:00:00+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/freshness_test_dag.py', '--cfg-path', '/tmp/tmprykfep6_']
[2024-04-01T10:04:58.400+0000] {standard_task_runner.py:88} INFO - Job 189: Subtask run_model1
[2024-04-01T10:04:58.743+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___freshness.run_model1 scheduled__2024-03-15T05:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-01T10:04:59.416+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___freshness' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T05:00:00+00:00'
[2024-04-01T10:04:59.422+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T10:04:59.424+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models my_first_dbt_model my_second_dbt_model  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-01T10:04:59.494+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T10:05:43.201+0000] {subprocess.py:93} INFO - [0m10:05:43  Running with dbt=1.7.10
[2024-04-01T10:05:47.584+0000] {subprocess.py:93} INFO - [0m10:05:47  Registered adapter: postgres=1.7.10
[2024-04-01T10:05:48.887+0000] {subprocess.py:93} INFO - [0m10:05:48  Encountered an error:
[2024-04-01T10:05:48.888+0000] {subprocess.py:93} INFO - [Errno 5] Input/output error: '/opt/***/proj/models/example/my_first_dbt_model.sql'
[2024-04-01T10:05:48.894+0000] {subprocess.py:93} INFO - [0m10:05:48  Traceback (most recent call last):
[2024-04-01T10:05:48.895+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
[2024-04-01T10:05:48.896+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-04-01T10:05:48.897+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 76, in wrapper
[2024-04-01T10:05:48.898+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:05:48.899+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 169, in wrapper
[2024-04-01T10:05:48.900+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:05:48.902+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 198, in wrapper
[2024-04-01T10:05:48.904+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:05:48.905+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 245, in wrapper
[2024-04-01T10:05:48.909+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:05:48.919+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 271, in wrapper
[2024-04-01T10:05:48.932+0000] {subprocess.py:93} INFO -     ctx.obj["manifest"] = parse_manifest(
[2024-04-01T10:05:48.951+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 1798, in parse_manifest
[2024-04-01T10:05:48.956+0000] {subprocess.py:93} INFO -     manifest = ManifestLoader.get_full_manifest(
[2024-04-01T10:05:48.967+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 318, in get_full_manifest
[2024-04-01T10:05:48.972+0000] {subprocess.py:93} INFO -     manifest = loader.load()
[2024-04-01T10:05:48.984+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 365, in load
[2024-04-01T10:05:48.997+0000] {subprocess.py:93} INFO -     file_reader.read_files()
[2024-04-01T10:05:49.001+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 203, in read_files
[2024-04-01T10:05:49.007+0000] {subprocess.py:93} INFO -     self.read_files_for_project(project, file_types)
[2024-04-01T10:05:49.010+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 210, in read_files_for_project
[2024-04-01T10:05:49.015+0000] {subprocess.py:93} INFO -     project_files[file_type_info["parser"]] = read_files_for_parser(
[2024-04-01T10:05:49.048+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 158, in read_files_for_parser
[2024-04-01T10:05:49.053+0000] {subprocess.py:93} INFO -     source_files = get_source_files(
[2024-04-01T10:05:49.054+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 147, in get_source_files
[2024-04-01T10:05:49.062+0000] {subprocess.py:93} INFO -     file = load_source_file(fp, parse_file_type, project.project_name, saved_files)
[2024-04-01T10:05:49.067+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 75, in load_source_file
[2024-04-01T10:05:49.087+0000] {subprocess.py:93} INFO -     file_contents = load_file_contents(path.absolute_path, strip=True)
[2024-04-01T10:05:49.090+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/clients/system.py", line 97, in load_file_contents
[2024-04-01T10:05:49.108+0000] {subprocess.py:93} INFO -     with open(path, "rb") as handle:
[2024-04-01T10:05:49.109+0000] {subprocess.py:93} INFO - OSError: [Errno 5] Input/output error: '/opt/***/proj/models/example/my_first_dbt_model.sql'
[2024-04-01T10:05:49.110+0000] {subprocess.py:93} INFO - 
[2024-04-01T10:05:50.416+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-01T10:05:50.452+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-01T10:05:50.495+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag___freshness, task_id=run_model1, execution_date=20240315T050000, start_date=20240401T100458, end_date=20240401T100550
[2024-04-01T10:05:50.545+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 189 for task run_model1 (Bash command failed. The command returned a non-zero exit code 2.; 1228)
[2024-04-01T10:05:50.596+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T10:05:51.518+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
