[2024-04-08T10:31:21.586+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___dbt.run_model1 scheduled__2024-04-05T10:00:00+00:00 [queued]>
[2024-04-08T10:31:21.658+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___dbt.run_model1 scheduled__2024-04-05T10:00:00+00:00 [queued]>
[2024-04-08T10:31:21.667+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-08T10:31:21.826+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-04-05 10:00:00+00:00
[2024-04-08T10:31:21.863+0000] {standard_task_runner.py:60} INFO - Started process 75 to run task
[2024-04-08T10:31:21.897+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___dbt', 'run_model1', 'scheduled__2024-04-05T10:00:00+00:00', '--job-id', '425', '--raw', '--subdir', 'DAGS_FOLDER/freshness_test_dag.py', '--cfg-path', '/tmp/tmp1cy6qyf9']
[2024-04-08T10:31:21.943+0000] {standard_task_runner.py:88} INFO - Job 425: Subtask run_model1
[2024-04-08T10:31:22.567+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___dbt.run_model1 scheduled__2024-04-05T10:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-08T10:31:23.871+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___dbt' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-04-05T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-05T10:00:00+00:00'
[2024-04-08T10:31:23.912+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-08T10:31:23.931+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models my_first_dbt_model my_second_dbt_model  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-08T10:31:24.090+0000] {subprocess.py:86} INFO - Output:
[2024-04-08T10:32:16.427+0000] {subprocess.py:93} INFO - [0m10:32:16  Running with dbt=1.7.10
[2024-04-08T10:32:21.895+0000] {subprocess.py:93} INFO - [0m10:32:21  Registered adapter: postgres=1.7.10
[2024-04-08T10:32:43.642+0000] {subprocess.py:93} INFO - [0m10:32:43  Found 34 models, 2 operations, 6 tests, 1 source, 0 exposures, 0 metrics, 1407 macros, 0 groups, 0 semantic models
[2024-04-08T10:32:43.777+0000] {subprocess.py:93} INFO - [0m10:32:43
[2024-04-08T10:32:48.327+0000] {subprocess.py:93} INFO - [0m10:32:48
[2024-04-08T10:32:48.451+0000] {subprocess.py:93} INFO - [0m10:32:48  Running 1 on-run-start hook
[2024-04-08T10:32:50.641+0000] {subprocess.py:93} INFO - [0m10:32:50  1 of 1 START hook: elementary.on-run-start.0 ................................... [RUN]
[2024-04-08T10:32:50.657+0000] {subprocess.py:93} INFO - [0m10:32:50  1 of 1 OK hook: elementary.on-run-start.0 ...................................... [[32mOK[0m in 0.00s]
[2024-04-08T10:32:50.690+0000] {subprocess.py:93} INFO - [0m10:32:50
[2024-04-08T10:32:50.727+0000] {subprocess.py:93} INFO - [0m10:32:50  Concurrency: 1 threads (target='dev')
[2024-04-08T10:32:50.740+0000] {subprocess.py:93} INFO - [0m10:32:50
[2024-04-08T10:32:50.926+0000] {subprocess.py:93} INFO - [0m10:32:50  1 of 2 START sql table model public.my_first_dbt_model ......................... [RUN]
[2024-04-08T10:32:54.640+0000] {subprocess.py:93} INFO - [0m10:32:54  1 of 2 OK created sql table model public.my_first_dbt_model .................... [[32mSELECT 2[0m in 3.64s]
[2024-04-08T10:32:54.673+0000] {subprocess.py:93} INFO - [0m10:32:54  2 of 2 START sql view model public.my_second_dbt_model ......................... [RUN]
[2024-04-08T10:32:55.863+0000] {subprocess.py:93} INFO - [0m10:32:55  2 of 2 ERROR creating sql view model public.my_second_dbt_model ................ [[31mERROR[0m in 1.16s]
[2024-04-08T10:32:56.172+0000] {subprocess.py:93} INFO - [0m10:32:56
[2024-04-08T10:32:56.188+0000] {subprocess.py:93} INFO - [0m10:32:56  Running 1 on-run-end hook
[2024-04-08T10:33:12.002+0000] {subprocess.py:93} INFO - [0m10:33:12  1 of 1 START hook: elementary.on-run-end.0 ..................................... [RUN]
[2024-04-08T10:33:12.008+0000] {subprocess.py:93} INFO - [0m10:33:12  1 of 1 OK hook: elementary.on-run-end.0 ........................................ [[32mOK[0m in 0.00s]
[2024-04-08T10:33:12.013+0000] {subprocess.py:93} INFO - [0m10:33:12
[2024-04-08T10:33:12.048+0000] {subprocess.py:93} INFO - [0m10:33:12
[2024-04-08T10:33:12.053+0000] {subprocess.py:93} INFO - [0m10:33:12  Finished running 1 table model, 1 view model, 2 hooks in 0 hours 0 minutes and 28.24 seconds (28.24s).
[2024-04-08T10:33:12.319+0000] {subprocess.py:93} INFO - [0m10:33:12
[2024-04-08T10:33:12.325+0000] {subprocess.py:93} INFO - [0m10:33:12  [31mCompleted with 1 error and 0 warnings:[0m
[2024-04-08T10:33:12.334+0000] {subprocess.py:93} INFO - [0m10:33:12
[2024-04-08T10:33:12.351+0000] {subprocess.py:93} INFO - [0m10:33:12    Database Error in model my_second_dbt_model (models/example/my_second_dbt_model.sql)
[2024-04-08T10:33:12.352+0000] {subprocess.py:93} INFO -   ERREUR:  la relation Â« my_second_dbt_model Â» existe dÃ©jÃ 
[2024-04-08T10:33:12.353+0000] {subprocess.py:93} INFO -   compiled Code at target/run/proj/models/example/my_second_dbt_model.sql
[2024-04-08T10:33:12.363+0000] {subprocess.py:93} INFO - [0m10:33:12
[2024-04-08T10:33:12.375+0000] {subprocess.py:93} INFO - [0m10:33:12  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
[2024-04-08T10:33:14.150+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-08T10:33:14.190+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-08T10:33:14.217+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag___dbt, task_id=run_model1, execution_date=20240405T100000, start_date=20240408T103121, end_date=20240408T103314
[2024-04-08T10:33:14.285+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 425 for task run_model1 (Bash command failed. The command returned a non-zero exit code 1.; 75)
[2024-04-08T10:33:14.349+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T10:33:14.431+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
