[2024-03-25T12:19:40.204+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___dbt.run_model1 manual__2024-03-25T12:14:33.607737+00:00 [queued]>
[2024-03-25T12:19:40.217+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___dbt.run_model1 manual__2024-03-25T12:14:33.607737+00:00 [queued]>
[2024-03-25T12:19:40.218+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-25T12:19:40.245+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-03-25 12:14:33.607737+00:00
[2024-03-25T12:19:40.253+0000] {standard_task_runner.py:60} INFO - Started process 535 to run task
[2024-03-25T12:19:40.258+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___dbt', 'run_model1', 'manual__2024-03-25T12:14:33.607737+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmptu75q1zx']
[2024-03-25T12:19:40.263+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask run_model1
[2024-03-25T12:19:40.358+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___dbt.run_model1 manual__2024-03-25T12:14:33.607737+00:00 [running]> on host 62dc842f1ceb
[2024-03-25T12:19:40.504+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___dbt' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T12:14:33.607737+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T12:14:33.607737+00:00'
[2024-03-25T12:19:40.513+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-25T12:19:40.520+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models my_first_dbt_model  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-03-25T12:19:40.549+0000] {subprocess.py:86} INFO - Output:
[2024-03-25T12:19:46.881+0000] {subprocess.py:93} INFO - [0m12:19:46  Running with dbt=1.7.10
[2024-03-25T12:19:46.896+0000] {subprocess.py:93} INFO - [0m12:19:46  Encountered an error:
[2024-03-25T12:19:46.897+0000] {subprocess.py:93} INFO - Runtime Error
[2024-03-25T12:19:46.897+0000] {subprocess.py:93} INFO -   Could not find profile named 'proj'
[2024-03-25T12:19:47.777+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-03-25T12:19:47.802+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-03-25T12:19:47.808+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag___dbt, task_id=run_model1, execution_date=20240325T121433, start_date=20240325T121940, end_date=20240325T121947
[2024-03-25T12:19:47.840+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task run_model1 (Bash command failed. The command returned a non-zero exit code 2.; 535)
[2024-03-25T12:19:47.892+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T12:19:47.941+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
