[2024-04-01T10:36:29.271+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___fresness.run_model1 scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-04-01T10:36:29.368+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___fresness.run_model1 scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-04-01T10:36:29.370+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-01T10:36:29.483+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-03-26 00:00:00+00:00
[2024-04-01T10:36:29.502+0000] {standard_task_runner.py:60} INFO - Started process 544 to run task
[2024-04-01T10:36:29.559+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___fresness', 'run_model1', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpfnb5jmmj']
[2024-04-01T10:36:29.608+0000] {standard_task_runner.py:88} INFO - Job 256: Subtask run_model1
[2024-04-01T10:36:30.178+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___fresness.run_model1 scheduled__2024-03-26T00:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-01T10:36:30.828+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___fresness' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-04-01T10:36:30.843+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T10:36:30.846+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-01T10:36:30.932+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T10:37:02.573+0000] {subprocess.py:93} INFO - [0m10:37:02  Running with dbt=1.7.10
[2024-04-01T10:37:05.147+0000] {subprocess.py:93} INFO - [0m10:37:05  Registered adapter: postgres=1.7.10
[2024-04-01T10:37:24.591+0000] {subprocess.py:93} INFO - [0m10:37:24  Found 34 models, 2 operations, 5 tests, 1 source, 0 exposures, 0 metrics, 1407 macros, 0 groups, 0 semantic models
[2024-04-01T10:37:24.607+0000] {subprocess.py:93} INFO - [0m10:37:24  The selection criterion '--profiles-dir' does not match any nodes
[2024-04-01T10:37:24.612+0000] {subprocess.py:93} INFO - [0m10:37:24  Encountered an error:
[2024-04-01T10:37:24.612+0000] {subprocess.py:93} INFO - Non-relative patterns are unsupported
[2024-04-01T10:37:24.635+0000] {subprocess.py:93} INFO - [0m10:37:24  Traceback (most recent call last):
[2024-04-01T10:37:24.639+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
[2024-04-01T10:37:24.644+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-04-01T10:37:24.646+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 76, in wrapper
[2024-04-01T10:37:24.647+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:24.648+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 169, in wrapper
[2024-04-01T10:37:24.650+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:24.651+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 198, in wrapper
[2024-04-01T10:37:24.653+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:24.654+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 245, in wrapper
[2024-04-01T10:37:24.657+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:24.660+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 278, in wrapper
[2024-04-01T10:37:24.662+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:37:24.663+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/main.py", line 625, in run
[2024-04-01T10:37:24.664+0000] {subprocess.py:93} INFO -     results = task.run()
[2024-04-01T10:37:24.665+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 454, in run
[2024-04-01T10:37:24.666+0000] {subprocess.py:93} INFO -     self._runtime_initialize()
[2024-04-01T10:37:24.669+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/compile.py", line 147, in _runtime_initialize
[2024-04-01T10:37:24.671+0000] {subprocess.py:93} INFO -     super()._runtime_initialize()
[2024-04-01T10:37:24.672+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 147, in _runtime_initialize
[2024-04-01T10:37:24.675+0000] {subprocess.py:93} INFO -     self.job_queue = self.get_graph_queue()
[2024-04-01T10:37:24.677+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 140, in get_graph_queue
[2024-04-01T10:37:24.679+0000] {subprocess.py:93} INFO -     return selector.get_graph_queue(spec)
[2024-04-01T10:37:24.680+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 318, in get_graph_queue
[2024-04-01T10:37:24.681+0000] {subprocess.py:93} INFO -     selected_nodes = self.get_selected(spec)
[2024-04-01T10:37:24.683+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 309, in get_selected
[2024-04-01T10:37:24.684+0000] {subprocess.py:93} INFO -     selected_nodes, indirect_only = self.select_nodes(spec)
[2024-04-01T10:37:24.688+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 158, in select_nodes
[2024-04-01T10:37:24.695+0000] {subprocess.py:93} INFO -     direct_nodes, indirect_nodes = self.select_nodes_recursively(spec)
[2024-04-01T10:37:24.697+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:37:24.698+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:24.699+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:37:24.700+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:24.702+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:37:24.703+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:24.706+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:37:24.710+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:24.713+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:37:24.718+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:24.719+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:37:24.720+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:37:24.721+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 128, in select_nodes_recursively
[2024-04-01T10:37:24.723+0000] {subprocess.py:93} INFO -     direct_nodes, indirect_nodes = self.get_nodes_from_criteria(spec)
[2024-04-01T10:37:24.724+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 82, in get_nodes_from_criteria
[2024-04-01T10:37:24.726+0000] {subprocess.py:93} INFO -     collected = self.select_included(nodes, spec)
[2024-04-01T10:37:24.729+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 68, in select_included
[2024-04-01T10:37:24.740+0000] {subprocess.py:93} INFO -     return set(method.search(included_nodes, spec.value))
[2024-04-01T10:37:24.743+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector_methods.py", line 413, in search
[2024-04-01T10:37:24.747+0000] {subprocess.py:93} INFO -     paths = set(p.relative_to(root) for p in root.glob(selector))
[2024-04-01T10:37:24.749+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector_methods.py", line 413, in <genexpr>
[2024-04-01T10:37:24.751+0000] {subprocess.py:93} INFO -     paths = set(p.relative_to(root) for p in root.glob(selector))
[2024-04-01T10:37:24.757+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pathlib.py", line 1138, in glob
[2024-04-01T10:37:24.759+0000] {subprocess.py:93} INFO -     raise NotImplementedError("Non-relative patterns are unsupported")
[2024-04-01T10:37:24.760+0000] {subprocess.py:93} INFO - NotImplementedError: Non-relative patterns are unsupported
[2024-04-01T10:37:24.763+0000] {subprocess.py:93} INFO - 
[2024-04-01T10:37:25.886+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-01T10:37:25.922+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-01T10:37:25.937+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag___fresness, task_id=run_model1, execution_date=20240326T000000, start_date=20240401T103629, end_date=20240401T103725
[2024-04-01T10:37:26.245+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 256 for task run_model1 (Bash command failed. The command returned a non-zero exit code 2.; 544)
[2024-04-01T10:37:26.322+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T10:37:26.402+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
