[2024-04-01T09:51:54.690+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___dbt.run_model1 scheduled__2024-04-01T01:00:00+00:00 [queued]>
[2024-04-01T09:51:54.723+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___dbt.run_model1 scheduled__2024-04-01T01:00:00+00:00 [queued]>
[2024-04-01T09:51:54.738+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-04-01T09:51:54.799+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-04-01 01:00:00+00:00
[2024-04-01T09:51:54.814+0000] {standard_task_runner.py:60} INFO - Started process 395 to run task
[2024-04-01T09:51:54.820+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___dbt', 'run_model1', 'scheduled__2024-04-01T01:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpg2cy6x3v']
[2024-04-01T09:51:54.827+0000] {standard_task_runner.py:88} INFO - Job 96: Subtask run_model1
[2024-04-01T09:51:55.188+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___dbt.run_model1 scheduled__2024-04-01T01:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-01T09:51:55.631+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___dbt' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T01:00:00+00:00'
[2024-04-01T09:51:55.644+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T09:51:55.654+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-01T09:51:55.791+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T09:52:26.726+0000] {subprocess.py:93} INFO - [0m09:52:26  Running with dbt=1.7.10
[2024-04-01T09:52:30.791+0000] {subprocess.py:93} INFO - [0m09:52:30  Registered adapter: postgres=1.7.10
[2024-04-01T09:52:34.344+0000] {subprocess.py:93} INFO - [0m09:52:34  Encountered an error:
[2024-04-01T09:52:34.348+0000] {subprocess.py:93} INFO - [Errno 5] Input/output error: '/opt/***/proj/dbt_packages/dbt_date/macros/calendar_date/round_timestamp.sql'
[2024-04-01T09:52:34.410+0000] {subprocess.py:93} INFO - [0m09:52:34  Traceback (most recent call last):
[2024-04-01T09:52:34.411+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
[2024-04-01T09:52:34.412+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-04-01T09:52:34.413+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 76, in wrapper
[2024-04-01T09:52:34.414+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:52:34.417+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 169, in wrapper
[2024-04-01T09:52:34.419+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:52:34.420+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 198, in wrapper
[2024-04-01T09:52:34.422+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:52:34.423+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 245, in wrapper
[2024-04-01T09:52:34.424+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T09:52:34.425+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 271, in wrapper
[2024-04-01T09:52:34.427+0000] {subprocess.py:93} INFO -     ctx.obj["manifest"] = parse_manifest(
[2024-04-01T09:52:34.430+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 1798, in parse_manifest
[2024-04-01T09:52:34.445+0000] {subprocess.py:93} INFO -     manifest = ManifestLoader.get_full_manifest(
[2024-04-01T09:52:34.446+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 318, in get_full_manifest
[2024-04-01T09:52:34.458+0000] {subprocess.py:93} INFO -     manifest = loader.load()
[2024-04-01T09:52:34.461+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/manifest.py", line 365, in load
[2024-04-01T09:52:34.462+0000] {subprocess.py:93} INFO -     file_reader.read_files()
[2024-04-01T09:52:34.463+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 203, in read_files
[2024-04-01T09:52:34.466+0000] {subprocess.py:93} INFO -     self.read_files_for_project(project, file_types)
[2024-04-01T09:52:34.477+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 210, in read_files_for_project
[2024-04-01T09:52:34.484+0000] {subprocess.py:93} INFO -     project_files[file_type_info["parser"]] = read_files_for_parser(
[2024-04-01T09:52:34.516+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 158, in read_files_for_parser
[2024-04-01T09:52:34.524+0000] {subprocess.py:93} INFO -     source_files = get_source_files(
[2024-04-01T09:52:34.541+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/read_files.py", line 134, in get_source_files
[2024-04-01T09:52:34.562+0000] {subprocess.py:93} INFO -     fp_list = filesystem_search(project, paths, extension, ignore_spec)
[2024-04-01T09:52:34.565+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/parser/search.py", line 74, in filesystem_search
[2024-04-01T09:52:34.570+0000] {subprocess.py:93} INFO -     for result in find_matching(root, relative_dirs, ext, ignore_spec):
[2024-04-01T09:52:34.582+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/clients/system.py", line 79, in find_matching
[2024-04-01T09:52:34.592+0000] {subprocess.py:93} INFO -     modification_time = os.path.getmtime(absolute_path)
[2024-04-01T09:52:34.598+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/genericpath.py", line 55, in getmtime
[2024-04-01T09:52:34.601+0000] {subprocess.py:93} INFO -     return os.stat(filename).st_mtime
[2024-04-01T09:52:34.604+0000] {subprocess.py:93} INFO - OSError: [Errno 5] Input/output error: '/opt/***/proj/dbt_packages/dbt_date/macros/calendar_date/round_timestamp.sql'
[2024-04-01T09:52:34.617+0000] {subprocess.py:93} INFO - 
[2024-04-01T09:52:38.939+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-01T09:52:38.993+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-01T09:52:39.030+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag___dbt, task_id=run_model1, execution_date=20240401T010000, start_date=20240401T095154, end_date=20240401T095239
[2024-04-01T09:52:39.105+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 96 for task run_model1 (Bash command failed. The command returned a non-zero exit code 2.; 395)
[2024-04-01T09:52:39.180+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T09:52:39.400+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
