[2024-04-01T11:55:09.937+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag___fresh___freshnes_test.dbt_data_quality_checks scheduled__0001-04-09T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
