[2024-04-08T10:38:51.685+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___dbt.dbt_data_quality_checks scheduled__2024-04-04T10:00:00+00:00 [queued]>
[2024-04-08T10:38:51.706+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___dbt.dbt_data_quality_checks scheduled__2024-04-04T10:00:00+00:00 [queued]>
[2024-04-08T10:38:51.709+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-08T10:38:51.760+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_data_quality_checks> on 2024-04-04 10:00:00+00:00
[2024-04-08T10:38:51.776+0000] {standard_task_runner.py:60} INFO - Started process 308 to run task
[2024-04-08T10:38:51.793+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___dbt', 'dbt_data_quality_checks', 'scheduled__2024-04-04T10:00:00+00:00', '--job-id', '438', '--raw', '--subdir', 'DAGS_FOLDER/freshness_test_dag.py', '--cfg-path', '/tmp/tmpionzixgn']
[2024-04-08T10:38:51.800+0000] {standard_task_runner.py:88} INFO - Job 438: Subtask dbt_data_quality_checks
[2024-04-08T10:38:51.948+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___dbt.dbt_data_quality_checks scheduled__2024-04-04T10:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-08T10:38:52.197+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___dbt' AIRFLOW_CTX_TASK_ID='dbt_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-04T10:00:00+00:00'
[2024-04-08T10:38:52.204+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-08T10:38:52.206+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-08T10:38:52.242+0000] {subprocess.py:86} INFO - Output:
[2024-04-08T10:38:59.994+0000] {subprocess.py:93} INFO - [0m10:38:59  Running with dbt=1.7.10
[2024-04-08T10:39:00.810+0000] {subprocess.py:93} INFO - [0m10:39:00  Registered adapter: postgres=1.7.10
[2024-04-08T10:39:12.600+0000] {subprocess.py:93} INFO - [0m10:39:12  Found 34 models, 2 operations, 6 tests, 1 source, 0 exposures, 0 metrics, 1407 macros, 0 groups, 0 semantic models
[2024-04-08T10:39:12.607+0000] {subprocess.py:93} INFO - [0m10:39:12
[2024-04-08T10:39:13.244+0000] {subprocess.py:93} INFO - [0m10:39:13
[2024-04-08T10:39:13.247+0000] {subprocess.py:93} INFO - [0m10:39:13  Running 1 on-run-start hook
[2024-04-08T10:39:13.560+0000] {subprocess.py:93} INFO - [0m10:39:13  1 of 1 START hook: elementary.on-run-start.0 ................................... [RUN]
[2024-04-08T10:39:13.562+0000] {subprocess.py:93} INFO - [0m10:39:13  1 of 1 OK hook: elementary.on-run-start.0 ...................................... [[32mOK[0m in 0.00s]
[2024-04-08T10:39:13.564+0000] {subprocess.py:93} INFO - [0m10:39:13
[2024-04-08T10:39:13.571+0000] {subprocess.py:93} INFO - [0m10:39:13  Concurrency: 1 threads (target='dev')
[2024-04-08T10:39:13.574+0000] {subprocess.py:93} INFO - [0m10:39:13
[2024-04-08T10:39:13.594+0000] {subprocess.py:93} INFO - [0m10:39:13  1 of 6 START test elementary_freshness_anomalies_raw_orders_creation_date ...... [RUN]
[2024-04-08T10:39:14.498+0000] {subprocess.py:93} INFO - [0m10:39:14  Elementary: Started running data monitors on: POSTGRES.PUBLIC.RAW_ORDERS
[2024-04-08T10:39:15.546+0000] {subprocess.py:93} INFO - [0m10:39:15  Elementary: Finished running data monitors on: POSTGRES.PUBLIC.RAW_ORDERS
[2024-04-08T10:39:16.782+0000] {subprocess.py:93} INFO - [0m10:39:16  1 of 6 PASS elementary_freshness_anomalies_raw_orders_creation_date ............ [[32mPASS[0m in 3.19s]
[2024-04-08T10:39:16.791+0000] {subprocess.py:93} INFO - [0m10:39:16  2 of 6 START test not_null_my_first_dbt_model_id ............................... [RUN]
[2024-04-08T10:39:17.080+0000] {subprocess.py:93} INFO - [0m10:39:17  2 of 6 FAIL 1 not_null_my_first_dbt_model_id ................................... [[31mFAIL 1[0m in 0.28s]
[2024-04-08T10:39:17.092+0000] {subprocess.py:93} INFO - [0m10:39:17  3 of 6 START test not_null_my_second_dbt_model_id .............................. [RUN]
[2024-04-08T10:39:17.347+0000] {subprocess.py:93} INFO - [0m10:39:17  3 of 6 PASS not_null_my_second_dbt_model_id .................................... [[32mPASS[0m in 0.25s]
[2024-04-08T10:39:17.357+0000] {subprocess.py:93} INFO - [0m10:39:17  4 of 6 START test not_null_raw_orders_creation_date ............................ [RUN]
[2024-04-08T10:39:17.585+0000] {subprocess.py:93} INFO - [0m10:39:17  4 of 6 PASS not_null_raw_orders_creation_date .................................. [[32mPASS[0m in 0.23s]
[2024-04-08T10:39:17.593+0000] {subprocess.py:93} INFO - [0m10:39:17  5 of 6 START test unique_my_first_dbt_model_id ................................. [RUN]
[2024-04-08T10:39:17.842+0000] {subprocess.py:93} INFO - [0m10:39:17  5 of 6 PASS unique_my_first_dbt_model_id ....................................... [[32mPASS[0m in 0.25s]
[2024-04-08T10:39:17.850+0000] {subprocess.py:93} INFO - [0m10:39:17  6 of 6 START test unique_my_second_dbt_model_id ................................ [RUN]
[2024-04-08T10:39:18.053+0000] {subprocess.py:93} INFO - [0m10:39:18  6 of 6 PASS unique_my_second_dbt_model_id ...................................... [[32mPASS[0m in 0.20s]
[2024-04-08T10:39:18.161+0000] {subprocess.py:93} INFO - [0m10:39:18
[2024-04-08T10:39:18.163+0000] {subprocess.py:93} INFO - [0m10:39:18  Running 1 on-run-end hook
[2024-04-08T10:39:24.197+0000] {subprocess.py:93} INFO - [0m10:39:24  1 of 1 START hook: elementary.on-run-end.0 ..................................... [RUN]
[2024-04-08T10:39:24.201+0000] {subprocess.py:93} INFO - [0m10:39:24  1 of 1 OK hook: elementary.on-run-end.0 ........................................ [[32mOK[0m in 0.00s]
[2024-04-08T10:39:24.205+0000] {subprocess.py:93} INFO - [0m10:39:24
[2024-04-08T10:39:24.235+0000] {subprocess.py:93} INFO - [0m10:39:24
[2024-04-08T10:39:24.238+0000] {subprocess.py:93} INFO - [0m10:39:24  Finished running 6 tests, 2 hooks in 0 hours 0 minutes and 11.62 seconds (11.62s).
[2024-04-08T10:39:24.604+0000] {subprocess.py:93} INFO - [0m10:39:24
[2024-04-08T10:39:24.607+0000] {subprocess.py:93} INFO - [0m10:39:24  [31mCompleted with 1 error and 0 warnings:[0m
[2024-04-08T10:39:24.610+0000] {subprocess.py:93} INFO - [0m10:39:24
[2024-04-08T10:39:24.614+0000] {subprocess.py:93} INFO - [0m10:39:24  [31mFailure in test not_null_my_first_dbt_model_id (models/example/schema.yml)[0m
[2024-04-08T10:39:24.617+0000] {subprocess.py:93} INFO - [0m10:39:24    Got 1 result, configured to fail if != 0
[2024-04-08T10:39:24.621+0000] {subprocess.py:93} INFO - [0m10:39:24
[2024-04-08T10:39:24.624+0000] {subprocess.py:93} INFO - [0m10:39:24    compiled Code at target/compiled/proj/models/example/schema.yml/not_null_my_first_dbt_model_id.sql
[2024-04-08T10:39:24.628+0000] {subprocess.py:93} INFO - [0m10:39:24
[2024-04-08T10:39:24.631+0000] {subprocess.py:93} INFO - [0m10:39:24  Done. PASS=5 WARN=0 ERROR=1 SKIP=0 TOTAL=6
[2024-04-08T10:39:26.492+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-08T10:39:26.546+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-08T10:39:26.580+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag___dbt, task_id=dbt_data_quality_checks, execution_date=20240404T100000, start_date=20240408T103851, end_date=20240408T103926
[2024-04-08T10:39:26.660+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 438 for task dbt_data_quality_checks (Bash command failed. The command returned a non-zero exit code 1.; 308)
[2024-04-08T10:39:26.707+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T10:39:26.795+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
