[2024-04-01T10:09:47.833+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: freshness___dbt.run_model1 scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-01T10:09:47.914+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: freshness___dbt.run_model1 scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-01T10:09:47.919+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-01T10:09:48.044+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-03-29 00:00:00+00:00
[2024-04-01T10:09:48.054+0000] {standard_task_runner.py:60} INFO - Started process 1517 to run task
[2024-04-01T10:09:48.083+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'freshness___dbt', 'run_model1', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/freshness_dag.py', '--cfg-path', '/tmp/tmp06807mcr']
[2024-04-01T10:09:48.106+0000] {standard_task_runner.py:88} INFO - Job 217: Subtask run_model1
[2024-04-01T10:09:48.422+0000] {task_command.py:423} INFO - Running <TaskInstance: freshness___dbt.run_model1 scheduled__2024-03-29T00:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-04-01T10:09:48.982+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='freshness___dbt' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-04-01T10:09:48.990+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T10:09:48.994+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-04-01T10:09:49.132+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T10:10:22.893+0000] {subprocess.py:93} INFO - [0m10:10:22  Running with dbt=1.7.10
[2024-04-01T10:10:25.902+0000] {subprocess.py:93} INFO - [0m10:10:25  Registered adapter: postgres=1.7.10
[2024-04-01T10:10:44.744+0000] {subprocess.py:93} INFO - [0m10:10:44  Found 34 models, 2 operations, 5 tests, 1 source, 0 exposures, 0 metrics, 1407 macros, 0 groups, 0 semantic models
[2024-04-01T10:10:44.756+0000] {subprocess.py:93} INFO - [0m10:10:44  The selection criterion '--profiles-dir' does not match any nodes
[2024-04-01T10:10:44.762+0000] {subprocess.py:93} INFO - [0m10:10:44  Encountered an error:
[2024-04-01T10:10:44.764+0000] {subprocess.py:93} INFO - Non-relative patterns are unsupported
[2024-04-01T10:10:44.777+0000] {subprocess.py:93} INFO - [0m10:10:44  Traceback (most recent call last):
[2024-04-01T10:10:44.778+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
[2024-04-01T10:10:44.779+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-04-01T10:10:44.781+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 76, in wrapper
[2024-04-01T10:10:44.782+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:10:44.784+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 169, in wrapper
[2024-04-01T10:10:44.786+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:10:44.787+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 198, in wrapper
[2024-04-01T10:10:44.788+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:10:44.791+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 245, in wrapper
[2024-04-01T10:10:44.792+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:10:44.793+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 278, in wrapper
[2024-04-01T10:10:44.795+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-04-01T10:10:44.797+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/cli/main.py", line 625, in run
[2024-04-01T10:10:44.798+0000] {subprocess.py:93} INFO -     results = task.run()
[2024-04-01T10:10:44.802+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 454, in run
[2024-04-01T10:10:44.804+0000] {subprocess.py:93} INFO -     self._runtime_initialize()
[2024-04-01T10:10:44.805+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/compile.py", line 147, in _runtime_initialize
[2024-04-01T10:10:44.807+0000] {subprocess.py:93} INFO -     super()._runtime_initialize()
[2024-04-01T10:10:44.809+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 147, in _runtime_initialize
[2024-04-01T10:10:44.811+0000] {subprocess.py:93} INFO -     self.job_queue = self.get_graph_queue()
[2024-04-01T10:10:44.813+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/task/runnable.py", line 140, in get_graph_queue
[2024-04-01T10:10:44.815+0000] {subprocess.py:93} INFO -     return selector.get_graph_queue(spec)
[2024-04-01T10:10:44.817+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 318, in get_graph_queue
[2024-04-01T10:10:44.819+0000] {subprocess.py:93} INFO -     selected_nodes = self.get_selected(spec)
[2024-04-01T10:10:44.820+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 309, in get_selected
[2024-04-01T10:10:44.822+0000] {subprocess.py:93} INFO -     selected_nodes, indirect_only = self.select_nodes(spec)
[2024-04-01T10:10:44.824+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 158, in select_nodes
[2024-04-01T10:10:44.826+0000] {subprocess.py:93} INFO -     direct_nodes, indirect_nodes = self.select_nodes_recursively(spec)
[2024-04-01T10:10:44.828+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:10:44.830+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:10:44.832+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:10:44.834+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:10:44.836+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:10:44.837+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:10:44.838+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:10:44.840+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:10:44.841+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in select_nodes_recursively
[2024-04-01T10:10:44.842+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:10:44.844+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 130, in <listcomp>
[2024-04-01T10:10:44.845+0000] {subprocess.py:93} INFO -     bundles = [self.select_nodes_recursively(component) for component in spec]
[2024-04-01T10:10:44.847+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 128, in select_nodes_recursively
[2024-04-01T10:10:44.849+0000] {subprocess.py:93} INFO -     direct_nodes, indirect_nodes = self.get_nodes_from_criteria(spec)
[2024-04-01T10:10:44.851+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 82, in get_nodes_from_criteria
[2024-04-01T10:10:44.853+0000] {subprocess.py:93} INFO -     collected = self.select_included(nodes, spec)
[2024-04-01T10:10:44.855+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector.py", line 68, in select_included
[2024-04-01T10:10:44.856+0000] {subprocess.py:93} INFO -     return set(method.search(included_nodes, spec.value))
[2024-04-01T10:10:44.858+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector_methods.py", line 413, in search
[2024-04-01T10:10:44.859+0000] {subprocess.py:93} INFO -     paths = set(p.relative_to(root) for p in root.glob(selector))
[2024-04-01T10:10:44.860+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/dbt/graph/selector_methods.py", line 413, in <genexpr>
[2024-04-01T10:10:44.861+0000] {subprocess.py:93} INFO -     paths = set(p.relative_to(root) for p in root.glob(selector))
[2024-04-01T10:10:44.865+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/pathlib.py", line 1138, in glob
[2024-04-01T10:10:44.867+0000] {subprocess.py:93} INFO -     raise NotImplementedError("Non-relative patterns are unsupported")
[2024-04-01T10:10:44.868+0000] {subprocess.py:93} INFO - NotImplementedError: Non-relative patterns are unsupported
[2024-04-01T10:10:44.870+0000] {subprocess.py:93} INFO - 
[2024-04-01T10:10:46.085+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-01T10:10:46.132+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-01T10:10:46.155+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=freshness___dbt, task_id=run_model1, execution_date=20240329T000000, start_date=20240401T100947, end_date=20240401T101046
[2024-04-01T10:10:46.479+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 217 for task run_model1 (Bash command failed. The command returned a non-zero exit code 2.; 1517)
[2024-04-01T10:10:46.515+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T10:10:46.634+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
