[2024-03-25T12:14:09.193+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___dbt.run_model1 scheduled__2024-03-21T00:00:00+00:00 [queued]>
[2024-03-25T12:14:09.268+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___dbt.run_model1 scheduled__2024-03-21T00:00:00+00:00 [queued]>
[2024-03-25T12:14:09.304+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-25T12:14:09.557+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_model1> on 2024-03-21 00:00:00+00:00
[2024-03-25T12:14:09.620+0000] {standard_task_runner.py:60} INFO - Started process 356 to run task
[2024-03-25T12:14:09.643+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___dbt', 'run_model1', 'scheduled__2024-03-21T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpez9qr7tc']
[2024-03-25T12:14:09.678+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask run_model1
[2024-03-25T12:14:10.239+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___dbt.run_model1 scheduled__2024-03-21T00:00:00+00:00 [running]> on host 62dc842f1ceb
[2024-03-25T12:14:10.902+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___dbt' AIRFLOW_CTX_TASK_ID='run_model1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-21T00:00:00+00:00'
[2024-03-25T12:14:10.913+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-25T12:14:10.921+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --models my_first_dbt_model  --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-03-25T12:14:11.013+0000] {subprocess.py:86} INFO - Output:
[2024-03-25T12:14:11.054+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/***/.local/bin/dbt: No such file or directory
[2024-03-25T12:14:11.067+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-25T12:14:11.157+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-25T12:14:11.181+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag___dbt, task_id=run_model1, execution_date=20240321T000000, start_date=20240325T121409, end_date=20240325T121411
[2024-03-25T12:14:11.331+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 26 for task run_model1 (Bash command failed. The command returned a non-zero exit code 127.; 356)
[2024-03-25T12:14:11.387+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T12:14:11.592+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
