[2024-04-01T10:00:13.924+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag___dbt.run_model1 scheduled__2024-03-30T07:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
