[2024-03-25T12:25:22.032+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag___dbt.dbt_data_quality_checks manual__2024-03-25T12:24:46.758421+00:00 [queued]>
[2024-03-25T12:25:22.047+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag___dbt.dbt_data_quality_checks manual__2024-03-25T12:24:46.758421+00:00 [queued]>
[2024-03-25T12:25:22.048+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-25T12:25:22.072+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_data_quality_checks> on 2024-03-25 12:24:46.758421+00:00
[2024-03-25T12:25:22.081+0000] {standard_task_runner.py:60} INFO - Started process 695 to run task
[2024-03-25T12:25:22.087+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag___dbt', 'dbt_data_quality_checks', 'manual__2024-03-25T12:24:46.758421+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpq4gmbz9w']
[2024-03-25T12:25:22.093+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask dbt_data_quality_checks
[2024-03-25T12:25:22.173+0000] {task_command.py:423} INFO - Running <TaskInstance: dag___dbt.dbt_data_quality_checks manual__2024-03-25T12:24:46.758421+00:00 [running]> on host 62dc842f1ceb
[2024-03-25T12:25:22.329+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag___dbt' AIRFLOW_CTX_TASK_ID='dbt_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T12:24:46.758421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T12:24:46.758421+00:00'
[2024-03-25T12:25:22.332+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-25T12:25:22.334+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/proj']
[2024-03-25T12:25:22.350+0000] {subprocess.py:86} INFO - Output:
[2024-03-25T12:25:28.233+0000] {subprocess.py:93} INFO - [0m12:25:28  Running with dbt=1.7.10
[2024-03-25T12:25:29.213+0000] {subprocess.py:93} INFO - [0m12:25:29  Registered adapter: postgres=1.7.10
[2024-03-25T12:25:41.521+0000] {subprocess.py:93} INFO - [0m12:25:41  Found 32 models, 2 operations, 4 tests, 0 sources, 0 exposures, 0 metrics, 1407 macros, 0 groups, 0 semantic models
[2024-03-25T12:25:41.531+0000] {subprocess.py:93} INFO - [0m12:25:41
[2024-03-25T12:25:42.460+0000] {subprocess.py:93} INFO - [0m12:25:42
[2024-03-25T12:25:42.467+0000] {subprocess.py:93} INFO - [0m12:25:42  Running 1 on-run-start hook
[2024-03-25T12:25:42.975+0000] {subprocess.py:93} INFO - [0m12:25:42  1 of 1 START hook: elementary.on-run-start.0 ................................... [RUN]
[2024-03-25T12:25:42.978+0000] {subprocess.py:93} INFO - [0m12:25:42  1 of 1 OK hook: elementary.on-run-start.0 ...................................... [[32mOK[0m in 0.00s]
[2024-03-25T12:25:42.980+0000] {subprocess.py:93} INFO - [0m12:25:42
[2024-03-25T12:25:42.987+0000] {subprocess.py:93} INFO - [0m12:25:42  Concurrency: 1 threads (target='dev')
[2024-03-25T12:25:42.991+0000] {subprocess.py:93} INFO - [0m12:25:42
[2024-03-25T12:25:43.024+0000] {subprocess.py:93} INFO - [0m12:25:43  1 of 4 START test not_null_my_first_dbt_model_id ............................... [RUN]
[2024-03-25T12:25:44.166+0000] {subprocess.py:93} INFO - [0m12:25:44  1 of 4 FAIL 1 not_null_my_first_dbt_model_id ................................... [[31mFAIL 1[0m in 1.14s]
[2024-03-25T12:25:44.175+0000] {subprocess.py:93} INFO - [0m12:25:44  2 of 4 START test not_null_my_second_dbt_model_id .............................. [RUN]
[2024-03-25T12:25:44.540+0000] {subprocess.py:93} INFO - [0m12:25:44  2 of 4 PASS not_null_my_second_dbt_model_id .................................... [[32mPASS[0m in 0.36s]
[2024-03-25T12:25:44.560+0000] {subprocess.py:93} INFO - [0m12:25:44  3 of 4 START test unique_my_first_dbt_model_id ................................. [RUN]
[2024-03-25T12:25:44.979+0000] {subprocess.py:93} INFO - [0m12:25:44  3 of 4 PASS unique_my_first_dbt_model_id ....................................... [[32mPASS[0m in 0.41s]
[2024-03-25T12:25:44.990+0000] {subprocess.py:93} INFO - [0m12:25:44  4 of 4 START test unique_my_second_dbt_model_id ................................ [RUN]
[2024-03-25T12:25:45.352+0000] {subprocess.py:93} INFO - [0m12:25:45  4 of 4 PASS unique_my_second_dbt_model_id ...................................... [[32mPASS[0m in 0.36s]
[2024-03-25T12:25:45.488+0000] {subprocess.py:93} INFO - [0m12:25:45
[2024-03-25T12:25:45.491+0000] {subprocess.py:93} INFO - [0m12:25:45  Running 1 on-run-end hook
[2024-03-25T12:25:53.325+0000] {subprocess.py:93} INFO - [0m12:25:53  1 of 1 START hook: elementary.on-run-end.0 ..................................... [RUN]
[2024-03-25T12:25:53.329+0000] {subprocess.py:93} INFO - [0m12:25:53  1 of 1 OK hook: elementary.on-run-end.0 ........................................ [[32mOK[0m in 0.00s]
[2024-03-25T12:25:53.332+0000] {subprocess.py:93} INFO - [0m12:25:53
[2024-03-25T12:25:53.349+0000] {subprocess.py:93} INFO - [0m12:25:53
[2024-03-25T12:25:53.352+0000] {subprocess.py:93} INFO - [0m12:25:53  Finished running 4 tests, 2 hooks in 0 hours 0 minutes and 11.81 seconds (11.81s).
[2024-03-25T12:25:53.486+0000] {subprocess.py:93} INFO - [0m12:25:53
[2024-03-25T12:25:53.489+0000] {subprocess.py:93} INFO - [0m12:25:53  [31mCompleted with 1 error and 0 warnings:[0m
[2024-03-25T12:25:53.492+0000] {subprocess.py:93} INFO - [0m12:25:53
[2024-03-25T12:25:53.495+0000] {subprocess.py:93} INFO - [0m12:25:53  [31mFailure in test not_null_my_first_dbt_model_id (models/example/schema.yml)[0m
[2024-03-25T12:25:53.498+0000] {subprocess.py:93} INFO - [0m12:25:53    Got 1 result, configured to fail if != 0
[2024-03-25T12:25:53.501+0000] {subprocess.py:93} INFO - [0m12:25:53
[2024-03-25T12:25:53.505+0000] {subprocess.py:93} INFO - [0m12:25:53    compiled Code at target/compiled/proj/models/example/schema.yml/not_null_my_first_dbt_model_id.sql
[2024-03-25T12:25:53.507+0000] {subprocess.py:93} INFO - [0m12:25:53
[2024-03-25T12:25:53.510+0000] {subprocess.py:93} INFO - [0m12:25:53  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2024-03-25T12:25:54.624+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-25T12:25:54.652+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-25T12:25:54.660+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag___dbt, task_id=dbt_data_quality_checks, execution_date=20240325T122446, start_date=20240325T122522, end_date=20240325T122554
[2024-03-25T12:25:54.707+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task dbt_data_quality_checks (Bash command failed. The command returned a non-zero exit code 1.; 695)
[2024-03-25T12:25:54.734+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T12:25:54.784+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
